[versions]

[libraries]
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-junit = "androidx.test.ext:junit:1.1.5"
androidx-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-composeBom = "androidx.compose:compose-bom:2023.01.00"
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }
androidx-lifecycleViewmodelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.2.2"

material = "com.google.android.material:material:1.8.0"

junit = "junit:junit:4.13.2"

coil = "io.coil-kt:coil-compose:2.2.2"

glide-compose = "com.github.bumptech.glide:compose:1.0.0-alpha.3"
glide-transformations = "jp.wasabeef:glide-transformations:4.3.0"
